/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WebBusinessCard {
    'email': string;
    'jobPosition': string;
    'linkedInProfile': string;
    'name': string;
    'phone': string;
    'website': string;
  }
  interface WebBusinessCardAttributes extends StencilHTMLAttributes {
    'email'?: string;
    'jobPosition'?: string;
    'linkedInProfile'?: string;
    'name'?: string;
    'phone'?: string;
    'website'?: string;
  }

  interface WebCountriesFinder {
    'keyword': string;
  }
  interface WebCountriesFinderAttributes extends StencilHTMLAttributes {
    'keyword'?: string;
  }

  interface WebFancyImage {
    'imageAlt': string;
    'imageStyle': string;
    'imageURL': string;
  }
  interface WebFancyImageAttributes extends StencilHTMLAttributes {
    'imageAlt'?: string;
    'imageStyle'?: string;
    'imageURL'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WebBusinessCard': Components.WebBusinessCard;
    'WebCountriesFinder': Components.WebCountriesFinder;
    'WebFancyImage': Components.WebFancyImage;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'web-business-card': Components.WebBusinessCardAttributes;
    'web-countries-finder': Components.WebCountriesFinderAttributes;
    'web-fancy-image': Components.WebFancyImageAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLWebBusinessCardElement extends Components.WebBusinessCard, HTMLStencilElement {}
  var HTMLWebBusinessCardElement: {
    prototype: HTMLWebBusinessCardElement;
    new (): HTMLWebBusinessCardElement;
  };

  interface HTMLWebCountriesFinderElement extends Components.WebCountriesFinder, HTMLStencilElement {}
  var HTMLWebCountriesFinderElement: {
    prototype: HTMLWebCountriesFinderElement;
    new (): HTMLWebCountriesFinderElement;
  };

  interface HTMLWebFancyImageElement extends Components.WebFancyImage, HTMLStencilElement {}
  var HTMLWebFancyImageElement: {
    prototype: HTMLWebFancyImageElement;
    new (): HTMLWebFancyImageElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'web-business-card': HTMLWebBusinessCardElement
    'web-countries-finder': HTMLWebCountriesFinderElement
    'web-fancy-image': HTMLWebFancyImageElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'web-business-card': HTMLWebBusinessCardElement;
    'web-countries-finder': HTMLWebCountriesFinderElement;
    'web-fancy-image': HTMLWebFancyImageElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
