/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BusinessCard {
    'email': string;
    'jobPosition': string;
    'linkedInProfile': string;
    'name': string;
    'phone': string;
    'website': string;
  }
  interface BusinessCardAttributes extends StencilHTMLAttributes {
    'email'?: string;
    'jobPosition'?: string;
    'linkedInProfile'?: string;
    'name'?: string;
    'phone'?: string;
    'website'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BusinessCard': Components.BusinessCard;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'business-card': Components.BusinessCardAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLBusinessCardElement extends Components.BusinessCard, HTMLStencilElement {}
  var HTMLBusinessCardElement: {
    prototype: HTMLBusinessCardElement;
    new (): HTMLBusinessCardElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'business-card': HTMLBusinessCardElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'business-card': HTMLBusinessCardElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
